travis:
  secure:
    BINSTAR_TOKEN: PPlZu3ou1M7rtqzvszLzNupJqNXPyl8KLbTu871UhLozagMCyzVhr4pN1oY2VQ3KrPU5OdTTZxx2pQxQ0mHe2HPnBLcO0QETswnCFLuUeQprJHqi7DvfQP1b+1ODSAwNRsQ7VKx09PZ5s1A5OXKPdO/Jeu+JCHtZ01z6SbP8Nh6NkGduLrTneHGlEkQasQUEABHrvRi7n6Tkali60eJUoWoMHNC/iF4IAOZIaY76DmXgVezka6FZIl+yXsojfj1u3LFSsjOQfsF4TgAnYCTTxLIYuzQGJi3qTHzZQncA7eH8z+ysKZtVZQgTvD+9pIOUZYQPze8u4/EB5/+JxDPdp1rbtHbbh9MHaxiif9BVFBWd9LSSEz5H2yUnfb9iPuunewfoH7l5rMXOiZNeeBk+IQpZUCd5KT4LP76a0116HyNPdvmbHLseo122mA+9beqUUQZh9V0VWE3BhpmIYyqO3iz5v462JONK19ktAOzkfEbkMwdCOChYILq+UQce03RIQdhzgU21OkyFu+cVC67lySdqsFCR2HONQ3u3bp83shyRvD6nveq1q84X6/OqZbQSh3CaN/YnJ39+joQg7CW18+TKg/NCsBKAlhX/b5PLlF3RqlQgPG6/4nCFFUVIffmGDm6OYEo5pt7fnlcir2dTh9xEzLZ83Dy9I9tRmLZuQbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
